export const siteText = {
  nav: {
    brand: 'CYNA',
    brandLabel: 'Accueil CYNA',
    searchPlaceholder: 'Rechercher une solution, un service ou un besoin',
    searchButton: 'Rechercher',
    searchHint: 'Recherche catalogue bientot disponible',
    cartLabel: 'Panier',
    cartHint: 'Voir votre panier',
    primaryLinks: [
      { label: 'Accueil', to: '/' },
      { label: 'Categories', to: '/categories' },
      { label: 'Produits', to: '/products' },
      { label: 'Contact', to: '/contact' },
    ],
    authLinks: [
      { label: 'Se connecter', to: '/login' },
      { label: "S'inscrire", to: '/register' },
    ],
    mobileLinks: [
      { label: 'Se connecter', to: '/login' },
      { label: "S'inscrire", to: '/register' },
      { label: 'Contact', to: '/contact' },
      { label: 'CGU', to: '/cgu' },
      { label: 'Mentions legales', to: '/mentions-legales' },
      { label: 'A propos de CYNA', to: '/a-propos' },
    ],
    mobileLinksGuest: [
      { label: 'Se connecter', to: '/login' },
      { label: "S'inscrire", to: '/register' },
      { label: 'Contact', to: '/contact' },
      { label: 'CGU', to: '/cgu' },
      { label: 'Mentions legales', to: '/mentions-legales' },
      { label: 'A propos de CYNA', to: '/a-propos' },
    ],
    mobileLinksAuth: [
      { label: 'Mon espace client', to: '/espace-client' },
      { label: 'Mes commandes', to: '/espace-client', state: { tab: 'orders' } },
      { label: 'Contact', to: '/contact' },
      { label: 'CGU', to: '/cgu' },
      { label: 'Mentions legales', to: '/mentions-legales' },
      { label: 'A propos de CYNA', to: '/a-propos' },
      { label: 'Se deconnecter', action: 'logout' },
    ],
    accountLabel: 'Mon espace',
    accountHint: 'Acceder a votre espace client',
    logoutLabel: 'Se deconnecter',
    greetingFallback: 'Bienvenue',
  },
  home: {
    slides: [
      { eyebrow: 'SOC manage', title: 'Gardez la maitrise de votre securite sans alourdir vos equipes.', copy: 'CYNA combine supervision, analyse et accompagnement.', cta: 'Decouvrir nos offres', to: '/products', visualTitle: 'Un pilotage clair', visualItems: ['Surveillance 24/7', 'Analystes dedies', 'Alertes prioritaires'] },
      { eyebrow: 'Protection postes', title: 'Detectez plus vite, contenez mieux.', copy: 'Nos solutions endpoint protegent les usages reels.', cta: 'Voir les categories', to: '/categories', visualTitle: 'Une reponse adaptee', visualItems: ['Detection comportementale', 'Aide remediation', 'Mise en oeuvre progressive'] },
      { eyebrow: 'Cloud & XDR', title: 'Un catalogue cyber concu pour structurer vos priorites.', copy: 'CYNA aide les directions IT a choisir.', cta: 'Voir top produits', to: '/products', visualTitle: 'Des parcours simples', visualItems: ['Comparaison claire', 'Accompagnement', 'Vision multi-besoins'] },
    ],
    intro: {
      eyebrow: 'La cybersecurite, plus simple',
      title: 'Des solutions cyber claires et actionnables.',
      copy: 'CYNA construit une experience plus lisible.',
      points: [
        { title: 'Choisir sans se perdre', copy: "Une presentation plus claire des offres." },
        { title: 'Structurer vos priorites', copy: 'Des categories lisibles.' },
        { title: 'Avancer progressivement', copy: 'Une base SPA propre.' },
      ],
    },
    categories: {
      title: 'Nos categories',
      copy: 'Explorez les grandes familles de solutions CYNA.',
      meta: 'Voir toutes les categories',
      error: 'Les categories sont temporairement indisponibles.',
      fallbackDescription: 'Une categorie CYNA pour structurer votre demarche cyber.',
      chip: 'Voir la categorie',
    },
    products: {
      title: 'Top Produits',
      copy: 'Une selection courte des offres les plus visibles.',
      meta: 'Voir tous les produits',
      error: 'Les top produits sont temporairement indisponibles.',
      fallbackPrice: 'Sur devis',
      fallbackCategory: 'Selection CYNA',
      status: 'Mis en avant',
    },
  },
  footer: {
    title: 'CYNA',
    copy: 'CYNA accompagne les entreprises dans le choix de solutions cyber lisibles.',
    legalTitle: 'Liens legaux',
    legalLinks: [
      { label: 'Mentions legales', to: '/mentions-legales' },
      { label: 'CGU', to: '/cgu' },
      { label: 'A propos de CYNA', to: '/a-propos' },
      { label: 'Contact', to: '/contact' },
    ],
    followTitle: 'Nous suivre',
    followLinks: [
      { label: 'LinkedIn', href: '#' },
      { label: 'Twitter / X', href: '#' },
      { label: 'GitHub', href: '#' },
    ],
    socialLinks: [
      { label: 'LinkedIn', href: 'https://www.linkedin.com', external: true },
      { label: 'YouTube', href: 'https://www.youtube.com', external: true },
      { label: 'X', href: 'https://x.com', external: true },
    ],
    copyright: '(c) {year} CYNA-IT - Tous droits reserves.',
  },
  pages: {
    categories: {
      eyebrow: 'Catalogue CYNA',
      title: 'Toutes nos categories de cybersecurite',
      copy: 'Selectionnez une categorie pour decouvrir les solutions associees.',
      error: 'Les categories sont temporairement indisponibles.',
      primary: "Retour a l'accueil",
      secondary: 'Voir les produits',
    },
    products: {
      eyebrow: 'Catalogue CYNA',
      title: 'Decouvrez tous nos services',
      copy: 'Filtrez le catalogue pour identifier la solution adaptee.',
      error: 'Les produits sont temporairement indisponibles.',
      empty: "Aucun produit ne correspond a votre recherche.",
      searchPlaceholder: 'Rechercher un produit...',
      categoryAll: 'Toutes les categories',
      sortLabel: 'Trier par',
      sortPriority: 'Pertinence',
      sortPriceAsc: 'Prix croissant',
      sortPriceDesc: 'Prix decroissant',
      sortNameAsc: 'Nom (A-Z)',
      submit: 'Filtrer',
      reset: 'Reinitialiser',
      previous: 'Precedent',
      next: 'Suivant',
      pageInfo: 'Page {current} sur {total}',
      fallbackPrice: 'Sur devis',
      fallbackCategory: 'Solution CYNA',
      detail: 'Voir le produit',
      primary: "Retour a l'accueil",
      secondary: 'Voir les categories',
    },
    productDetail: {
      back: 'Retour',
      error: 'Produit introuvable.',
      fallbackCategory: 'Solution CYNA',
      quantityLabel: 'Quantite',
      durationLabel: 'Duree',
      month: 'mois',
      months: 'mois',
      addToCart: 'Ajouter au panier',
      continue: 'Continuer mes achats',
      addedToCart: 'Produit ajoute au panier.',
      addError: 'Impossible d\'ajouter au panier.',
    },
    cart: {
      eyebrow: 'Votre panier',
      title: 'Recapitulatif de votre selection',
      copy: 'Modifiez les quantites ou supprimez des lignes avant de commander.',
      loading: 'Chargement de votre panier...',
      emptyTitle: 'Votre panier est vide',
      emptyCopy: 'Decouvrez nos solutions de cybersecurite et ajoutez-les a votre panier.',
      browseCatalog: 'Parcourir le catalogue',
      duration: 'Duree',
      month: 'mois',
      months: 'mois',
      quantity: 'Quantite',
      remove: 'Supprimer',
      subtotal: 'Sous-total',
      taxesNote: 'TVA incluse. La facturation finale sera calculee a la commande.',
      checkout: 'Passer commande',
      loginNeeded: 'Connectez-vous pour finaliser votre commande.',
    },
    checkout: {
      eyebrow: 'Finalisation',
      title: 'Confirmez votre commande',
      copy: 'Selectionnez une adresse de facturation et validez.',
      addressLegend: 'Adresse de facturation',
      label: 'Libelle',
      line1: 'Adresse',
      line2: 'Complement',
      postalCode: 'Code postal',
      city: 'Ville',
      country: 'Pays',
      firstname: 'Prenom',
      lastname: 'Nom',
      region: 'Region',
      mobile: 'Telephone mobile',
      addAddress: 'Saisir une nouvelle adresse',
      cancel: 'Annuler',
      paymentLegend: 'Mode de paiement',
      paymentNote: 'Paiement securise par Stripe. Utilisez une carte de test pour valider le flux local.',
      summary: 'Recapitulatif',
      total: 'Total',
      submit: 'Valider la commande',
      preparePayment: 'Continuer vers le paiement',
      submitting: 'Envoi en cours...',
      paymentSubmit: 'Payer maintenant',
      paymentSubmitting: 'Paiement en cours...',
      back: 'Retour au panier',
      addressNeeded: 'Une adresse de facturation est requise.',
      emptyCartError: 'Votre panier est vide.',
      cartSyncError: 'Votre panier doit etre synchronise avant le paiement. Revenez au panier puis reessayez.',
      stripeKeyMissing: 'La cle publique Stripe VITE_STRIPE_PUBLISHABLE_KEY est manquante.',
      paymentError: 'Le paiement a echoue. Veuillez verifier vos informations.',
      paymentPending: 'Le paiement est en cours de traitement. Veuillez patienter avant de reessayer.',
      genericError: 'Une erreur est survenue. Veuillez reessayer.',
    },
    orderConfirmation: {
      loading: 'Chargement de la commande...',
      eyebrow: 'Commande confirmee',
      title: 'Merci pour votre commande !',
      copy: 'Votre commande {ref} a bien ete enregistree. Un email de confirmation vous sera envoye.',
      reference: 'Reference',
      total: 'Total',
      status: 'Statut',
      backToAccount: 'Voir mes commandes',
      continue: 'Continuer mes achats',
      errorTitle: 'Commande introuvable',
      errorCopy: "Cette commande n'est pas disponible ou ne vous appartient pas.",
    },
    notFound: {
      eyebrow: 'Page introuvable',
      title: "Cette page n'existe pas.",
      copy: "Revenez a l'accueil pour poursuivre.",
      cta: "Retour a l'accueil",
    },
    privateArea: {
      eyebrow: 'Espace client',
      title: 'Bienvenue dans votre espace CYNA',
      copy: 'Votre connexion est bien prise en compte.',
      cta: "Retour a l'accueil",
      identityTitle: 'Vos informations',
      identityFirstname: 'Prenom',
      identityLastname: 'Nom',
      identityEmail: 'E-mail',
      identityRoles: 'Roles',
      identityVerified: 'E-mail verifie',
      identityVerifiedYes: 'Oui',
      identityVerifiedNo: 'Non',
      logoutLabel: 'Se deconnecter',
    },
    account: {
      eyebrow: 'Espace client',
      title: 'Votre espace CYNA',
      greeting: 'Bonjour',
      logout: 'Se deconnecter',
      tabProfile: 'Profil',
      tabOrders: 'Commandes',
      tabAddresses: 'Adresses',
      tabPayments: 'Paiement',
      tabSecurity: 'Securite',
      tabMail: 'Mail',
      profileFirstname: 'Prenom',
      profileLastname: 'Nom',
      profileEmail: 'E-mail',
      profileVerified: 'E-mail verifie',
      profileRoles: 'Roles',
      yes: 'Oui',
      no: 'Non',
      loading: 'Chargement...',
      ordersEmpty: "Vous n'avez pas encore de commande.",
      view: 'Voir',
      addressesEmpty: "Vous n'avez pas encore enregistre d'adresse.",
      firstname: 'Prenom',
      lastname: 'Nom',
      fieldRegion: 'Region',
      fieldMobile: 'Telephone mobile',
      addAddress: 'Ajouter une adresse',
      delete: 'Supprimer',
      fieldLabel: 'Libelle',
      fieldLine1: 'Adresse',
      fieldLine2: 'Complement',
      fieldPostal: 'Code postal',
      fieldCity: 'Ville',
      fieldCountry: 'Pays',
      save: 'Enregistrer',
      cancel: 'Annuler',
      paymentsEmpty: "Aucune methode de paiement enregistree.",
      paymentsNote: "Demonstration : aucune donnee carte reelle n'est stockee. Seules les 4 derniers chiffres et l'expiration sont conserves.",
      addPayment: 'Ajouter un mode de paiement',
      paymentLabel: 'Libelle',
      paymentBrand: 'Marque',
      paymentInvalidLast4: 'Les 4 derniers chiffres doivent etre 4 chiffres.',
      paymentLast4: '4 derniers chiffres',
      paymentMonth: 'Mois exp.',
      paymentYear: 'Annee exp.',
      mailIntro: 'Connectez une adresse de destination et envoyez un e-mail de test via Brevo.',
      mailRecipient: 'Adresse de test',
      mailAccount: 'Compte connecte',
      mailSend: 'Envoyer le test',
      mailSending: 'Envoi...',
      mailSuccess: 'E-mail de test envoye a {email}.',
      genericError: "Une erreur est survenue. Veuillez reessayer.",
    },
    verifyEmail: {
      eyebrow: 'Verification e-mail',
      titlePending: 'Verification en cours...',
      copyPending: 'Nous validons votre adresse, merci de patienter.',
      titleSuccess: 'Adresse verifiee',
      copySuccess: 'Votre adresse e-mail est confirmee. Vous pouvez vous connecter.',
      titleError: 'Lien invalide ou expire',
      copyError: 'Le lien de verification est invalide ou a expire. Demandez-en un nouveau depuis votre espace client.',
      toLogin: 'Aller a la connexion',
    },
    forgotPassword: {
      eyebrow: 'Mot de passe oublie',
      title: 'Reinitialiser votre mot de passe',
      copy: 'Saisissez votre adresse, nous vous enverrons un lien de reinitialisation.',
      cardTitle: 'Mot de passe oublie',
      cardCopy: 'Indiquez votre adresse pour recevoir le lien.',
      emailLabel: 'Adresse e-mail',
      submit: 'Envoyer le lien',
      submitting: 'Envoi...',
      success: 'Si un compte est associe a cette adresse, un email vient d\'etre envoye.',
      invalidEmail: 'Adresse e-mail invalide.',
      back: 'Retour a la connexion',
      footerPrompt: 'Vous vous souvenez de votre mot de passe ?',
      footerAction: 'Se connecter',
    },
    resetPassword: {
      eyebrow: 'Reinitialisation',
      title: 'Choisissez un nouveau mot de passe',
      copy: 'Le lien recu par email vous a redirige ici. Definissez votre nouveau mot de passe.',
      cardTitle: 'Nouveau mot de passe',
      cardCopy: 'Saisissez et confirmez votre nouveau mot de passe.',
      passwordLabel: 'Nouveau mot de passe',
      confirmLabel: 'Confirmer le mot de passe',
      submit: 'Mettre a jour',
      submitting: 'Mise a jour...',
      success: 'Mot de passe mis a jour. Redirection vers la connexion...',
      tokenMissing: 'Lien invalide. Refaites une demande de reinitialisation.',
      weakPassword: 'Mot de passe trop faible : minimum {n} caracteres avec majuscule, minuscule, chiffre et special.',
      mismatch: 'Les mots de passe ne correspondent pas.',
      genericError: 'Impossible de mettre a jour le mot de passe.',
      helper: 'Minimum {n} caracteres avec majuscule, minuscule, chiffre et caractere special.',
      back: 'Retour a la connexion',
      footerPrompt: 'Vous vous souvenez de votre mot de passe ?',
      footerAction: 'Se connecter',
    },
    contact: {
      eyebrow: 'Contact',
      title: 'Contacter l\'equipe CYNA',
      copy: 'Une question, un besoin specifique ? Ecrivez-nous, nous reviendrons rapidement vers vous.',
      nameLabel: 'Nom complet',
      emailLabel: 'Adresse e-mail',
      subjectLabel: 'Objet',
      messageLabel: 'Votre message',
      submit: 'Envoyer',
      submitting: 'Envoi...',
      success: 'Votre message a bien ete envoye. Notre equipe reviendra vers vous tres prochainement.',
      fieldsRequired: 'Veuillez remplir tous les champs.',
      invalidEmail: 'Adresse e-mail invalide.',
      genericError: "Impossible d'envoyer le message pour le moment.",
      teamTitle: 'Notre equipe',
      teamCopy: 'Le projet CYNA est porte par :',
      teamMembers: [
        'MIRONA Orian',
        'PLOQUIN Juliann',
        'LEONARD Donavan',
      ],
    },
    cgu: {
      eyebrow: 'Conditions generales',
      title: "Conditions Generales d'Utilisation",
      copy: "Ces conditions encadrent l'utilisation de la plateforme CYNA-IT et de ses services. En naviguant sur le site, vous acceptez les regles decrites ci-dessous.",
      lastUpdate: 'Derniere mise a jour : 19 mai 2026',
      articles: [
        {
          number: 'Article 1',
          title: "Objet et champ d'application",
          paragraphs: [
            "Les presentes Conditions Generales d'Utilisation (CGU) ont pour objet de definir les modalites et conditions dans lesquelles CYNA-IT met a disposition de ses utilisateurs la plateforme accessible a l'adresse cyna-it.fr ainsi que les services de cybersecurite associes.",
            "Toute utilisation du site implique l'acceptation pleine et entiere des presentes CGU. CYNA-IT se reserve le droit de les modifier a tout moment pour les adapter aux evolutions de la plateforme ou de la legislation en vigueur.",
          ],
        },
        {
          number: 'Article 2',
          title: 'Acces au site et aux services',
          paragraphs: [
            "L'acces au site est ouvert a tout utilisateur disposant d'une connexion Internet. Certaines fonctionnalites necessitent la creation d'un compte client securise via une adresse e-mail valide et un mot de passe robuste.",
            "CYNA-IT met tout en oeuvre pour assurer une disponibilite continue du service, mais ne peut etre tenue responsable des interruptions liees a la maintenance, aux attaques tierces ou a des cas de force majeure.",
            "L'utilisateur s'engage a proteger ses identifiants et a signaler sans delai toute utilisation frauduleuse de son compte aupres du support CYNA-IT.",
          ],
        },
        {
          number: 'Article 3',
          title: 'Responsabilites',
          paragraphs: [
            "L'utilisateur s'engage a utiliser la plateforme conformement aux lois en vigueur et a ne pas porter atteinte a la securite des systemes d'information de CYNA-IT ou de tiers.",
            "Toute tentative d'intrusion, d'analyse non autorisee, de retro-ingenierie ou de denis de service fera l'objet de poursuites judiciaires conformement aux articles 323-1 et suivants du Code penal.",
            "CYNA-IT ne saurait etre tenue responsable d'un mauvais usage des solutions de cybersecurite proposees ni des dommages indirects pouvant resulter d'une exploitation hors specifications.",
          ],
        },
        {
          number: 'Article 4',
          title: 'Propriete intellectuelle',
          paragraphs: [
            "L'ensemble des contenus presents sur le site (textes, logos, marques, graphismes, code source, illustrations) est la propriete exclusive de CYNA-IT ou de ses partenaires editeurs.",
            "Toute reproduction, representation, modification ou diffusion totale ou partielle des contenus, sans autorisation ecrite prealable, est strictement interdite et constitue un acte de contrefacon sanctionne par les articles L.335-2 et suivants du Code de la propriete intellectuelle.",
          ],
        },
        {
          number: 'Article 5',
          title: 'Droit applicable et juridiction',
          paragraphs: [
            "Les presentes CGU sont regies par le droit francais. Toute reclamation peut etre adressee au support CYNA-IT a l'adresse contact@cyna-it.fr.",
            "A defaut de resolution amiable, tout litige relatif a l'interpretation ou a l'execution des presentes sera soumis aux tribunaux competents du ressort de la Cour d'appel de Paris.",
          ],
        },
      ],
    },
    legal: {
      eyebrow: 'Mentions legales',
      title: 'Mentions legales',
      copy: 'Informations relatives a l\'editeur du site CYNA-IT, conformement a la loi n.2004-575 du 21 juin 2004 pour la confiance dans l\'economie numerique.',
      lastUpdate: 'Derniere mise a jour : 19 mai 2026',
      sections: [
        {
          title: "Editeur du site",
          items: [
            { label: 'Raison sociale', value: 'CYNA-IT SAS' },
            { label: 'Capital social', value: '100 000 EUR' },
            { label: 'Siege social', value: '12 rue de la Cybersecurite, 75011 Paris, France' },
            { label: 'RCS', value: 'Paris B 902 481 376' },
            { label: 'TVA intracommunautaire', value: 'FR 32 902481376' },
            { label: 'Directeur de la publication', value: 'M. Alexandre Vidal, President' },
            { label: 'Contact', value: 'contact@cyna-it.fr - 01 80 00 00 00' },
          ],
        },
        {
          title: "Hebergeur",
          items: [
            { label: 'Raison sociale', value: 'OVH SAS' },
            { label: 'Siege social', value: '2 rue Kellermann, 59100 Roubaix, France' },
            { label: 'Telephone', value: '+33 9 72 10 10 07' },
            { label: 'Site web', value: 'www.ovhcloud.com' },
          ],
        },
        {
          title: 'Propriete intellectuelle',
          paragraphs: [
            "L'ensemble du contenu de ce site (architecture, textes, illustrations, photographies, marques, logos, charte graphique) est la propriete exclusive de CYNA-IT ou de ses ayants droit.",
            "Toute reproduction integrale ou partielle de ces elements, par quelque procede que ce soit, sans autorisation expresse de CYNA-IT, est interdite et constituerait une contrefacon sanctionnee par les articles L.335-2 et suivants du Code de la propriete intellectuelle.",
          ],
        },
        {
          title: 'Donnees personnelles',
          paragraphs: [
            "CYNA-IT collecte et traite des donnees personnelles dans le respect du Reglement General sur la Protection des Donnees (RGPD) et de la loi Informatique et Libertes du 6 janvier 1978 modifiee.",
            "Les donnees collectees sont strictement necessaires a la gestion de votre compte, au traitement de vos commandes et a l'amelioration de nos services. Elles sont conservees pour la duree legale applicable.",
            "Conformement a la reglementation, vous disposez d'un droit d'acces, de rectification, d'opposition, de portabilite et de suppression sur vos donnees. Ces droits peuvent etre exerces a l'adresse dpo@cyna-it.fr.",
            "En cas de litige, vous avez la possibilite d'introduire une reclamation aupres de la CNIL (Commission Nationale de l'Informatique et des Libertes).",
          ],
        },
        {
          title: 'Cookies',
          paragraphs: [
            "Le site cyna-it.fr utilise des cookies strictement necessaires a son fonctionnement (authentification, panier) ainsi que des cookies de mesure d'audience anonymises.",
            "Vous pouvez a tout moment ajuster vos preferences via le bandeau de gestion des cookies ou les parametres de votre navigateur.",
          ],
        },
      ],
    },
    about: {
      eyebrow: 'A propos',
      title: 'CYNA-IT, la cybersecurite plus claire pour les entreprises',
      copy: "Depuis 2018, CYNA-IT accompagne les directions IT et metiers dans la selection, le deploiement et la supervision de solutions de cybersecurite adaptees a leurs enjeux reels.",
      missionTitle: 'Notre mission',
      missionParagraphs: [
        "Rendre la cybersecurite lisible, accessible et actionnable pour toutes les entreprises francaises, des PME industrielles aux ETI a forte exposition reglementaire.",
        "Notre conviction : un bon outil ne sert a rien sans un cadre clair. Chaque service CYNA-IT est pense pour s'integrer dans la realite operationnelle de nos clients, sans alourdir leurs equipes.",
      ],
      stats: [
        { value: '+180', label: 'Clients accompagnes' },
        { value: '24/7', label: 'Supervision SOC' },
        { value: '15 ans', label: "D'experience cyber cumulee" },
        { value: '100%', label: 'Equipe basee en France' },
      ],
      valuesTitle: 'Nos valeurs',
      values: [
        {
          title: 'Clarte',
          copy: 'Nous expliquons ce que nous proposons. Pas de jargon inutile, pas de promesses floues : des livrables concrets et mesurables.',
        },
        {
          title: 'Independance',
          copy: "Nous restons libres dans notre conseil. Nos recommandations sont guidees par votre contexte, pas par un editeur partenaire.",
        },
        {
          title: 'Proximite',
          copy: 'Un interlocuteur dedie, des points reguliers, une equipe joignable. La relation prime sur le contrat.',
        },
        {
          title: 'Exigence',
          copy: "La cybersecurite ne tolere pas l'a-peu-pres. Nous appliquons a nos livrables le meme niveau d'exigence que nous attendons de nos outils.",
        },
      ],
      ctaTitle: 'Discutons de votre projet',
      ctaCopy: 'Une question, un audit a planifier, un besoin urgent ? Notre equipe est joignable rapidement.',
      ctaPrimary: 'Nous contacter',
      ctaSecondary: 'Voir nos solutions',
    },
  },
  auth: {
    loginBenefits: ['Acces securise a votre espace client', 'Suivi de vos services', 'Gestion de votre compte'],
    registerBenefits: ['Creation simple et securisee', 'Suivi de vos abonnements', 'Acces a votre espace CYNA'],
    login: {
      eyebrow: 'Connexion',
      title: 'Se connecter a votre espace CYNA',
      copy: 'Accedez a vos services de cybersecurite.',
      cardTitle: 'Se connecter',
      cardCopy: 'Connectez-vous avec vos identifiants.',
      submit: 'Se connecter',
      submitting: 'Connexion...',
      emailLabel: 'Adresse e-mail',
      passwordLabel: 'Mot de passe',
      rememberMe: 'Se souvenir de moi',
      forgotPassword: 'Mot de passe oublie ?',
      divider: 'ou',
      google: 'Continuer avec Google',
      googleHint: 'Bientot disponible',
      googleStatus: 'Connexion Google bientot disponible',
      success: 'Connexion reussie. Redirection en cours...',
      twoFactorRequired: 'Saisissez votre code de securite pour terminer la connexion.',
      twoFactorEmailSent: 'Un code de securite a 6 chiffres vient de vous etre envoye par e-mail.',
      twoFactorCodeLabel: 'Code de securite',
      twoFactorSubmit: 'Valider le code',
      switchPrompt: "Vous n'avez pas encore de compte ?",
      switchAction: 'Creer un compte',
    },
    register: {
      eyebrow: 'Inscription',
      title: 'Creer votre compte CYNA',
      copy: 'Accedez a nos solutions et gerez vos abonnements.',
      cardTitle: "S'inscrire",
      cardCopy: "Renseignez vos informations pour preparer votre acces.",
      submit: 'Creer mon compte',
      submitting: 'Creation...',
      fullNameLabel: 'Nom complet',
      emailLabel: 'Adresse e-mail',
      passwordLabel: 'Mot de passe',
      confirmPasswordLabel: 'Confirmer le mot de passe',
      passwordHelp: 'Minimum 12 caracteres, avec majuscules, minuscules, chiffres et caracteres speciaux.',
      divider: 'ou',
      google: 'Continuer avec Google',
      googleHint: 'Bientot disponible',
      googleStatus: 'Inscription Google bientot disponible',
      info: 'Un e-mail de confirmation vous a ete envoye. Veuillez verifier votre boite de reception pour activer votre compte.',
      switchPrompt: 'Vous avez deja un compte ?',
      switchAction: 'Se connecter',
    },
  },
}
