export const siteText = {
  nav: {
    brand: 'CYNA',
    brandLabel: 'Accueil CYNA',
    searchPlaceholder: 'Rechercher une solution, un service ou un besoin',
    searchButton: 'Rechercher',
    searchHint: 'Recherche catalogue bientot disponible',
    cartLabel: 'Panier',
    cartHint: 'Voir votre panier',
    primaryLinks: [
      { label: 'Accueil', to: '/' },
      { label: 'Categories', to: '/categories' },
      { label: 'Produits', to: '/products' },
      { label: 'Contact', to: '/contact' },
    ],
    authLinks: [
      { label: 'Se connecter', to: '/login' },
      { label: "S'inscrire", to: '/register' },
    ],
    mobileLinks: [
      { label: 'Se connecter', to: '/login' },
      { label: "S'inscrire", to: '/register' },
      { label: 'Contact', to: '/contact' },
      { label: 'CGU', to: '/cgu' },
      { label: 'Mentions legales', to: '/mentions-legales' },
      { label: 'A propos de CYNA', to: '/a-propos' },
    ],
    mobileLinksGuest: [
      { label: 'Se connecter', to: '/login' },
      { label: "S'inscrire", to: '/register' },
      { label: 'Contact', to: '/contact' },
      { label: 'CGU', to: '/cgu' },
      { label: 'Mentions legales', to: '/mentions-legales' },
      { label: 'A propos', to: '/a-propos' },
    ],
    mobileLinksAuth: [
      { label: 'Mon espace client', to: '/espace-client' },
      { label: 'Mes commandes', to: '/espace-client', state: { tab: 'orders' } },
      { label: 'Contact', to: '/contact' },
      { label: 'CGU', to: '/cgu' },
      { label: 'Mentions legales', to: '/mentions-legales' },
      { label: 'A propos', to: '/a-propos' },
      { label: 'Se deconnecter', action: 'logout' },
    ],
    accountLabel: 'Mon espace',
    accountHint: 'Acceder a votre espace client',
    logoutLabel: 'Se deconnecter',
    greetingFallback: 'Bienvenue',
  },
  home: {
    slides: [
      { eyebrow: 'SOC manage', title: 'Gardez la maitrise de votre securite sans alourdir vos equipes.', copy: 'CYNA combine supervision, analyse et accompagnement.', cta: 'Decouvrir nos offres', to: '/products', visualTitle: 'Un pilotage clair', visualItems: ['Surveillance 24/7', 'Analystes dedies', 'Alertes prioritaires'] },
      { eyebrow: 'Protection postes', title: 'Detectez plus vite, contenez mieux.', copy: 'Nos solutions endpoint protegent les usages reels.', cta: 'Voir les categories', to: '/categories', visualTitle: 'Une reponse adaptee', visualItems: ['Detection comportementale', 'Aide remediation', 'Mise en oeuvre progressive'] },
      { eyebrow: 'Cloud & XDR', title: 'Un catalogue cyber concu pour structurer vos priorites.', copy: 'CYNA aide les directions IT a choisir.', cta: 'Voir top produits', to: '/products', visualTitle: 'Des parcours simples', visualItems: ['Comparaison claire', 'Accompagnement', 'Vision multi-besoins'] },
    ],
    intro: {
      eyebrow: 'La cybersecurite, plus simple',
      title: 'Des solutions cyber claires et actionnables.',
      copy: 'CYNA construit une experience plus lisible.',
      points: [
        { title: 'Choisir sans se perdre', copy: "Une presentation plus claire des offres." },
        { title: 'Structurer vos priorites', copy: 'Des categories lisibles.' },
        { title: 'Avancer progressivement', copy: 'Une base SPA propre.' },
      ],
    },
    categories: {
      title: 'Nos categories',
      copy: 'Explorez les grandes familles de solutions CYNA.',
      meta: 'Voir toutes les categories',
      error: 'Les categories sont temporairement indisponibles.',
      fallbackDescription: 'Une categorie CYNA pour structurer votre demarche cyber.',
      chip: 'Voir la categorie',
    },
    products: {
      title: 'Top Produits',
      copy: 'Une selection courte des offres les plus visibles.',
      meta: 'Voir tous les produits',
      error: 'Les top produits sont temporairement indisponibles.',
      fallbackPrice: 'Sur devis',
      fallbackCategory: 'Selection CYNA',
      status: 'Mis en avant',
    },
  },
  footer: {
    title: 'CYNA',
    copy: 'CYNA accompagne les entreprises dans le choix de solutions cyber lisibles.',
    informationsTitle: 'Informations',
    contactTitle: 'Contact',
    contactEmail: 'contact@cyna.fr',
    contactPhone: '01 80 00 00 00',
    legalLinksTitle: 'Liens legaux',
    legalLinks: [
      { label: 'CGU', to: '/cgu' },
      { label: 'Mentions legales', to: '/mentions-legales' },
      { label: 'A propos', to: '/a-propos' },
    ],
    socialLinksTitle: 'Nous suivre',
    socialLinks: [
      { label: 'LinkedIn', href: '#', external: true },
      { label: 'Twitter / X', href: '#', external: true },
      { label: 'GitHub', href: '#', external: true },
    ],
  },
  pages: {
    categories: {
      eyebrow: 'Catalogue CYNA',
      title: 'Toutes nos categories de cybersecurite',
      copy: 'Selectionnez une categorie pour decouvrir les solutions associees.',
      error: 'Les categories sont temporairement indisponibles.',
      primary: "Retour a l'accueil",
      secondary: 'Voir les produits',
    },
    products: {
      eyebrow: 'Catalogue CYNA',
      title: 'Decouvrez tous nos services',
      copy: 'Filtrez le catalogue pour identifier la solution adaptee.',
      error: 'Les produits sont temporairement indisponibles.',
      empty: "Aucun produit ne correspond a votre recherche.",
      searchPlaceholder: 'Rechercher un produit...',
      categoryAll: 'Toutes les categories',
      sortLabel: 'Trier par',
      sortPriority: 'Pertinence',
      sortPriceAsc: 'Prix croissant',
      sortPriceDesc: 'Prix decroissant',
      sortNameAsc: 'Nom (A-Z)',
      submit: 'Filtrer',
      reset: 'Reinitialiser',
      previous: 'Precedent',
      next: 'Suivant',
      pageInfo: 'Page {current} sur {total}',
      fallbackPrice: 'Sur devis',
      fallbackCategory: 'Solution CYNA',
      detail: 'Voir le produit',
      primary: "Retour a l'accueil",
      secondary: 'Voir les categories',
    },
    productDetail: {
      back: 'Retour',
      error: 'Produit introuvable.',
      fallbackCategory: 'Solution CYNA',
      quantityLabel: 'Quantite',
      durationLabel: 'Duree',
      month: 'mois',
      months: 'mois',
      addToCart: 'Ajouter au panier',
      continue: 'Continuer mes achats',
      addedToCart: 'Produit ajoute au panier.',
      addError: 'Impossible d\'ajouter au panier.',
    },
    cart: {
      eyebrow: 'Votre panier',
      title: 'Recapitulatif de votre selection',
      copy: 'Modifiez les quantites ou supprimez des lignes avant de commander.',
      loading: 'Chargement de votre panier...',
      emptyTitle: 'Votre panier est vide',
      emptyCopy: 'Decouvrez nos solutions de cybersecurite et ajoutez-les a votre panier.',
      browseCatalog: 'Parcourir le catalogue',
      duration: 'Duree',
      month: 'mois',
      months: 'mois',
      quantity: 'Quantite',
      remove: 'Supprimer',
      subtotal: 'Sous-total',
      taxesNote: 'TVA incluse. La facturation finale sera calculee a la commande.',
      checkout: 'Passer commande',
      loginNeeded: 'Connectez-vous pour finaliser votre commande.',
    },
    checkout: {
      eyebrow: 'Finalisation',
      title: 'Confirmez votre commande',
      copy: 'Selectionnez une adresse de facturation et validez.',
      addressLegend: 'Adresse de facturation',
      label: 'Libelle',
      line1: 'Adresse',
      line2: 'Complement',
      postalCode: 'Code postal',
      city: 'Ville',
      country: 'Pays',
      addAddress: 'Saisir une nouvelle adresse',
      cancel: 'Annuler',
      paymentLegend: 'Mode de paiement',
      paymentNote: 'Aucune methode enregistree. Vous pourrez en ajouter depuis votre espace client.',
      summary: 'Recapitulatif',
      total: 'Total',
      submit: 'Valider la commande',
      submitting: 'Envoi en cours...',
      back: 'Retour au panier',
      addressNeeded: 'Une adresse de facturation est requise.',
      emptyCartError: 'Votre panier est vide.',
      genericError: 'Une erreur est survenue. Veuillez reessayer.',
    },
    orderConfirmation: {
      loading: 'Chargement de la commande...',
      eyebrow: 'Commande confirmee',
      title: 'Merci pour votre commande !',
      copy: 'Votre commande {ref} a bien ete enregistree. Un email de confirmation vous sera envoye.',
      reference: 'Reference',
      total: 'Total',
      status: 'Statut',
      backToAccount: 'Voir mes commandes',
      continue: 'Continuer mes achats',
      errorTitle: 'Commande introuvable',
      errorCopy: "Cette commande n'est pas disponible ou ne vous appartient pas.",
    },
    notFound: {
      eyebrow: 'Page introuvable',
      title: "Cette page n'existe pas.",
      copy: "Revenez a l'accueil pour poursuivre.",
      cta: "Retour a l'accueil",
    },
    privateArea: {
      eyebrow: 'Espace client',
      title: 'Bienvenue dans votre espace CYNA',
      copy: 'Votre connexion est bien prise en compte.',
      cta: "Retour a l'accueil",
      identityTitle: 'Vos informations',
      identityFirstname: 'Prenom',
      identityLastname: 'Nom',
      identityEmail: 'E-mail',
      identityRoles: 'Roles',
      identityVerified: 'E-mail verifie',
      identityVerifiedYes: 'Oui',
      identityVerifiedNo: 'Non',
      logoutLabel: 'Se deconnecter',
    },
    account: {
      eyebrow: 'Espace client',
      title: 'Votre espace CYNA',
      greeting: 'Bonjour',
      logout: 'Se deconnecter',
      tabProfile: 'Profil',
      tabOrders: 'Commandes',
      tabAddresses: 'Adresses',
      tabPayments: 'Paiement',
      profileFirstname: 'Prenom',
      profileLastname: 'Nom',
      profileEmail: 'E-mail',
      profileVerified: 'E-mail verifie',
      profileRoles: 'Roles',
      yes: 'Oui',
      no: 'Non',
      loading: 'Chargement...',
      ordersEmpty: "Vous n'avez pas encore de commande.",
      view: 'Voir',
      addressesEmpty: "Vous n'avez pas encore enregistre d'adresse.",
      addAddress: 'Ajouter une adresse',
      delete: 'Supprimer',
      fieldLabel: 'Libelle',
      fieldLine1: 'Adresse',
      fieldLine2: 'Complement',
      fieldPostal: 'Code postal',
      fieldCity: 'Ville',
      fieldCountry: 'Pays',
      save: 'Enregistrer',
      cancel: 'Annuler',
      paymentsEmpty: "Aucune methode de paiement enregistree.",
      paymentsNote: "Demonstration : aucune donnee carte reelle n'est stockee. Seules les 4 derniers chiffres et l'expiration sont conserves.",
      addPayment: 'Ajouter un mode de paiement',
      paymentLabel: 'Libelle',
      paymentLast4: '4 derniers chiffres',
      paymentMonth: 'Mois exp.',
      paymentYear: 'Annee exp.',
      genericError: "Une erreur est survenue. Veuillez reessayer.",
    },
    verifyEmail: {
      eyebrow: 'Verification e-mail',
      titlePending: 'Verification en cours...',
      copyPending: 'Nous validons votre adresse, merci de patienter.',
      titleSuccess: 'Adresse verifiee',
      copySuccess: 'Votre adresse e-mail est confirmee. Vous pouvez vous connecter.',
      titleError: 'Lien invalide ou expire',
      copyError: 'Le lien de verification est invalide ou a expire. Demandez-en un nouveau depuis votre espace client.',
      toLogin: 'Aller a la connexion',
    },
    forgotPassword: {
      eyebrow: 'Mot de passe oublie',
      title: 'Reinitialiser votre mot de passe',
      copy: 'Saisissez votre adresse, nous vous enverrons un lien de reinitialisation.',
      cardTitle: 'Mot de passe oublie',
      cardCopy: 'Indiquez votre adresse pour recevoir le lien.',
      emailLabel: 'Adresse e-mail',
      submit: 'Envoyer le lien',
      submitting: 'Envoi...',
      success: 'Si un compte est associe a cette adresse, un email vient d\'etre envoye.',
      invalidEmail: 'Adresse e-mail invalide.',
      back: 'Retour a la connexion',
      footerPrompt: 'Vous vous souvenez de votre mot de passe ?',
      footerAction: 'Se connecter',
    },
    resetPassword: {
      eyebrow: 'Reinitialisation',
      title: 'Choisissez un nouveau mot de passe',
      copy: 'Le lien recu par email vous a redirige ici. Definissez votre nouveau mot de passe.',
      cardTitle: 'Nouveau mot de passe',
      cardCopy: 'Saisissez et confirmez votre nouveau mot de passe.',
      passwordLabel: 'Nouveau mot de passe',
      confirmLabel: 'Confirmer le mot de passe',
      submit: 'Mettre a jour',
      submitting: 'Mise a jour...',
      success: 'Mot de passe mis a jour. Redirection vers la connexion...',
      tokenMissing: 'Lien invalide. Refaites une demande de reinitialisation.',
      weakPassword: 'Mot de passe trop faible : minimum {n} caracteres avec majuscule, minuscule, chiffre et special.',
      mismatch: 'Les mots de passe ne correspondent pas.',
      genericError: 'Impossible de mettre a jour le mot de passe.',
      helper: 'Minimum {n} caracteres avec majuscule, minuscule, chiffre et caractere special.',
      back: 'Retour a la connexion',
      footerPrompt: 'Vous vous souvenez de votre mot de passe ?',
      footerAction: 'Se connecter',
    },
    cgu: {
      eyebrow: 'Conditions d\'utilisation',
      title: 'Conditions generales d\'utilisation',
      copy: 'En utilisant les services CYNA, vous acceptez les presentes conditions. Lisez-les attentivement avant tout acces a la Plateforme.',
      updated: 'Version 1.0 — Mai 2025. CYNA-IT SAS se reserve le droit de modifier ces CGU a tout moment avec notification prealable aux utilisateurs.',
      articles: [
        {
          id: 'art1',
          title: 'Article 1 — Objet',
          content: 'Les presentes Conditions Generales d\'Utilisation (CGU) regissent l\'acces et l\'utilisation de la plateforme CYNA-IT (ci-apres « la Plateforme »), editee par CYNA-IT SAS. La Plateforme permet aux entreprises de decouvrir, comparer et souscrire a des solutions de cybersecurite. Toute utilisation de la Plateforme implique l\'acceptation pleine et entiere des presentes CGU.',
        },
        {
          id: 'art2',
          title: 'Article 2 — Acces aux services',
          content: 'L\'acces a la Plateforme est ouvert a toute personne morale ou physique disposant d\'une capacite juridique suffisante. La creation d\'un compte necessite de fournir des informations exactes et a jour. CYNA-IT SAS se reserve le droit de suspendre ou de resilier tout compte en cas de non-respect des presentes CGU ou d\'utilisation frauduleuse de la Plateforme.',
        },
        {
          id: 'art3',
          title: 'Article 3 — Responsabilites',
          content: 'CYNA-IT SAS s\'engage a mettre en oeuvre les moyens necessaires pour assurer la disponibilite et la securite de la Plateforme. En cas d\'indisponibilite temporaire liee a des operations de maintenance ou a des evenements imprevus, la responsabilite de CYNA-IT SAS ne pourra etre engagee. L\'utilisateur est responsable de la confidentialite de ses identifiants et de toute activite realisee depuis son compte.',
        },
        {
          id: 'art4',
          title: 'Article 4 — Propriete intellectuelle',
          content: 'L\'ensemble des elements constituant la Plateforme (textes, images, logos, interfaces, code source) sont proteges par le droit de la propriete intellectuelle et restent la propriete exclusive de CYNA-IT SAS ou de ses partenaires. Toute reproduction, representation, modification ou distribution sans autorisation prealable ecrite est strictement interdite.',
        },
        {
          id: 'art5',
          title: 'Article 5 — Droit applicable et juridiction',
          content: 'Les presentes CGU sont soumises au droit francais. En cas de litige relatif a l\'interpretation ou a l\'execution des presentes CGU, les parties s\'engagent a rechercher une solution amiable. A defaut, le litige sera soumis a la competence exclusive du Tribunal de Commerce de Paris.',
        },
      ],
    },
    legal: {
      eyebrow: 'Transparence',
      title: 'Mentions legales',
      copy: 'Conformement a la loi n° 2004-575 du 21 juin 2004 pour la confiance dans l\'economie numerique, voici les informations legales relatives a la Plateforme CYNA.',
      sections: [
        {
          id: 'editeur',
          title: 'Editeur du site',
          lines: [
            'Raison sociale : CYNA-IT SAS',
            'Capital social : 10 000 €',
            'Siege social : 12 rue de la Securite Numerique, 75001 Paris, France',
            'SIRET : 123 456 789 00010',
            'RCS Paris : B 123 456 789',
            'Directeur de la publication : Nairo Yanes',
            'Contact : contact@cyna-it.fr',
          ],
        },
        {
          id: 'hebergeur',
          title: 'Hebergeur',
          lines: [
            'Raison sociale : OVH SAS',
            'Siege social : 2 rue Kellermann, 59100 Roubaix, France',
            'Site web : www.ovhcloud.com',
          ],
        },
        {
          id: 'pi',
          title: 'Propriete intellectuelle',
          lines: [
            'L\'ensemble du contenu de la Plateforme (textes, images, visuels, logos, icones, logiciels) est la propriete exclusive de CYNA-IT SAS, sauf mentions contraires.',
            'Toute reproduction totale ou partielle de ce contenu est strictement interdite sans autorisation prealable et ecrite de CYNA-IT SAS.',
            'Les marques et logos reproduits sur la Plateforme sont des marques deposees par leurs proprietaires respectifs.',
          ],
        },
        {
          id: 'donnees',
          title: 'Donnees personnelles',
          lines: [
            'CYNA-IT SAS collecte et traite des donnees personnelles dans le cadre de la fourniture de ses services, conformement au RGPD et a la loi Informatique et Libertes.',
            'Vous disposez d\'un droit d\'acces, de rectification, de suppression et de portabilite de vos donnees. Pour exercer ces droits, contactez-nous a : privacy@cyna-it.fr.',
            'Un Delegue a la Protection des Donnees (DPO) a ete designe. Vous pouvez le contacter a la meme adresse.',
          ],
        },
      ],
    },
    about: {
      eyebrow: 'Notre histoire',
      title: 'A propos de CYNA-IT',
      copy: 'CYNA-IT est nee d\'une conviction simple : la cybersecurite doit etre accessible, lisible et actionnee par tous les acteurs economiques, quelle que soit leur maturite.',
      missionTitle: 'Notre mission',
      missionCopy: 'Nous construisons une plateforme qui simplifie le choix des solutions cyber pour les entreprises. Chaque jour, des directions IT font face a une offre fragmentee, des discours techniques opaques et des decisions risquees. CYNA-IT repond a ce defi en proposant un catalogue structure, des comparaisons claires et un accompagnement oriente resultats. Notre ambition : devenir le partenaire de confiance des equipes IT qui veulent avancer sereinement en matiere de cybersecurite.',
      valuesTitle: 'Nos valeurs',
      values: [
        { title: 'Clarte', copy: 'Nous refusons le jargon inutile. Chaque offre est presentee de facon lisible et honnete.' },
        { title: 'Confiance', copy: 'La securite de nos clients est notre priorite absolue. Nous tenons nos engagements.' },
        { title: 'Pragmatisme', copy: 'Nous privilegions les solutions qui fonctionnent dans la vraie vie, pas seulement en laboratoire.' },
        { title: 'Accessibilite', copy: 'La cybersecurite n\'est pas reservee aux grandes entreprises. Nous rendons les meilleures solutions accessibles a tous.' },
      ],
      teamTitle: 'L\'equipe',
      team: [
        { name: 'Nairo Yanes', role: 'CEO & Co-fondateur', bio: 'Expert en cybersecurite avec 10 ans d\'experience en SOC et en architecture de securite. Nairo a dirige des equipes chez plusieurs ESN francaises avant de fonder CYNA-IT.' },
        { name: 'Sophie Marchand', role: 'CTO & Co-fondatrice', bio: 'Ancienne lead developer dans une scale-up fintech, Sophie apporte son expertise en architecture cloud et en developpement de plateformes SaaS securisees.' },
        { name: 'Thomas Beaumont', role: 'Responsable Produit', bio: 'Specialiste UX et product management, Thomas s\'assure que chaque parcours utilisateur sur la plateforme est intuitif et efficace.' },
        { name: 'Camille Dubois', role: 'Responsable Partenariats', bio: 'Ancienne consultante en cybersecurite, Camille gere les relations avec les editeurs de solutions et s\'assure de la qualite du catalogue CYNA-IT.' },
      ],
    },
    contact: {
      eyebrow: 'Contact',
      title: 'Contacter l\'equipe CYNA',
      copy: 'Une question, un besoin specifique ? Ecrivez-nous, nous reviendrons rapidement vers vous.',
      nameLabel: 'Nom complet',
      emailLabel: 'Adresse e-mail',
      subjectLabel: 'Objet',
      messageLabel: 'Votre message',
      submit: 'Envoyer',
      submitting: 'Envoi...',
      success: 'Votre message a bien ete envoye. Notre equipe reviendra vers vous tres prochainement.',
      fieldsRequired: 'Veuillez remplir tous les champs.',
      invalidEmail: 'Adresse e-mail invalide.',
      genericError: "Impossible d'envoyer le message pour le moment.",
    },
  },
  auth: {
    loginBenefits: ['Acces securise a votre espace client', 'Suivi de vos services', 'Gestion de votre compte'],
    registerBenefits: ['Creation simple et securisee', 'Suivi de vos abonnements', 'Acces a votre espace CYNA'],
    login: {
      eyebrow: 'Connexion',
      title: 'Se connecter a votre espace CYNA',
      copy: 'Accedez a vos services de cybersecurite.',
      cardTitle: 'Se connecter',
      cardCopy: 'Connectez-vous avec vos identifiants.',
      submit: 'Se connecter',
      submitting: 'Connexion...',
      emailLabel: 'Adresse e-mail',
      passwordLabel: 'Mot de passe',
      rememberMe: 'Se souvenir de moi',
      forgotPassword: 'Mot de passe oublie ?',
      divider: 'ou',
      google: 'Continuer avec Google',
      googleHint: 'Bientot disponible',
      googleStatus: 'Connexion Google bientot disponible',
      success: 'Connexion reussie. Redirection en cours...',
      switchPrompt: "Vous n'avez pas encore de compte ?",
      switchAction: 'Creer un compte',
    },
    register: {
      eyebrow: 'Inscription',
      title: 'Creer votre compte CYNA',
      copy: 'Accedez a nos solutions et gerez vos abonnements.',
      cardTitle: "S'inscrire",
      cardCopy: "Renseignez vos informations pour preparer votre acces.",
      submit: 'Creer mon compte',
      submitting: 'Creation...',
      fullNameLabel: 'Nom complet',
      emailLabel: 'Adresse e-mail',
      passwordLabel: 'Mot de passe',
      confirmPasswordLabel: 'Confirmer le mot de passe',
      passwordHelp: 'Minimum 12 caracteres, avec majuscules, minuscules, chiffres et caracteres speciaux.',
      divider: 'ou',
      google: 'Continuer avec Google',
      googleHint: 'Bientot disponible',
      googleStatus: 'Inscription Google bientot disponible',
      info: 'Un e-mail de confirmation vous a ete envoye. Veuillez verifier votre boite de reception pour activer votre compte.',
      switchPrompt: 'Vous avez deja un compte ?',
      switchAction: 'Se connecter',
    },
  },
}
